import random
import art

print(art.logo)
print("\n" * 10)

print("Welcome to the Number Guessing Game!")
print("I'm thinking of a number between 1 and 100.")


while True:
    difficulty = input("Choose a difficulty. Type 'easy' or 'hard': ").lower()

    if difficulty in ["easy", "hard"]:
        break
    else:
        print("Incorrect choice! Please enter again.")

print("Selected difficulty:", difficulty)

# Random number between 1 and 100 generated by system
random_number = random.randint(1, 100)
counter = 0

if difficulty == 'easy':
    counter = 10
else:
    counter = 5

while counter != 0:
    print(f"You have {counter} attempts remaining to guess the number.")
    guessed_number = int(input("Make a guess: "))

    if guessed_number > random_number:
        print("Too high.")
        print("Guess again")
        counter -= 1
    elif guessed_number < random_number:
        print("Too low.")
        print("Guess again")
        counter -= 1
    elif guessed_number == random_number:
        print(f"You got it! The answer was {random_number}")
        break

if counter == 0:
    print("You ran out of attempts!")